In [22]:
import pandas as pd
import numpy as np

In [16]:
quakes = pd.read_csv('data/parsed.csv')
quakes.dtypes

alert            object
cdi             float64
code             object
detail           object
dmin            float64
felt            float64
gap             float64
ids              object
mag             float64
magType          object
mmi             float64
net              object
nst             float64
place            object
rms             float64
sig               int64
sources          object
status           object
time              int64
title            object
tsunami           int64
type             object
types            object
tz              float64
updated           int64
url              object
parsed_place     object
dtype: object

In [17]:
quakes.head()

,alert,cdi,code,detail,dmin,felt,gap,ids,mag,magType,...,status,time,title,tsunami,type,types,tz,updated,url,parsed_place
0,NaN,NaN,37389218,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.008693,NaN,85.0,",ci37389218,",1.35,ml,...,automatic,1539475168010,"M 1.4 - 9km NE of Aguanga, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,",-480.0,1539475395144,https://earthquake.usgs.gov/earthquakes/eventp...,California
1,NaN,NaN,37389202,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.020030,NaN,79.0,",ci37389202,",1.29,ml,...,automatic,1539475129610,"M 1.3 - 9km NE of Aguanga, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,",-480.0,1539475253925,https://earthquake.usgs.gov/earthquakes/eventp...,California
2,NaN,4.4,37389194,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.021370,28.0,21.0,",ci37389194,",3.42,ml,...,automatic,1539475062610,"M 3.4 - 8km NE of Aguanga, CA",0,earthquake,",dyfi,focal-mechanism,geoserve,nearby-cities,o...",-480.0,1539536756176,https://earthquake.usgs.gov/earthquakes/eventp...,California
3,NaN,NaN,37389186,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.026180,NaN,39.0,",ci37389186,",0.44,ml,...,automatic,1539474978070,"M 0.4 - 9km NE of Aguanga, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,",-480.0,1539475196167,https://earthquake.usgs.gov/earthquakes/eventp...,California
4,NaN,NaN,73096941,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.077990,NaN,192.0,",nc73096941,",2.16,md,...,automatic,1539474716050,"M 2.2 - 10km NW of Avenal, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,scit...",-480.0,1539477547926,https://earthquake.usgs.gov/earthquakes/eventp...,California

## Question 1
Find the 95th percentile of earquake magnitude in Japan usin gthe mb magnitude type

In [44]:
print(np.quantile(quakes[(quakes.parsed_place == 'Japan') & (quakes.magType == 'mb')]['mag'], .95))

4.9

## Question 2
Find the percentage of earthquakes in Indonesia that were coupled with tsunamis

In [42]:
print(quakes[quakes.parsed_place == 'Indonesia']['tsunami'].mean())

0.23129251700680273

## Question 3
Calculate the summary statistics for earthquakes in Nevada

In [ ]:
quakes[quakes.parsed_place == "Nevada"].describe()

TypeError: Cannot interpret '<built-in function all>' as a data type

In [53]:
quakes[quakes.parsed_place == "Nevada"].describe(include=object)

,alert,code,detail,ids,magType,net,place,sources,status,title,type,types,url,parsed_place
count,0,681,681,681,681,681,681,681,681,681,681,681,681,681
unique,0,681,681,681,2,3,419,6,2,630,3,7,681,1
top,NaN,00660878,https://earthquake.usgs.gov/fdsnws/event/1/que...,",nn00660878,",ml,nn,"55km ENE of Beatty, Nevada",",nn,",reviewed,"M -0.3 - 55km ENE of Beatty, Nevada",earthquake,",geoserve,origin,phase-data,",https://earthquake.usgs.gov/earthquakes/eventp...,Nevada
freq,NaN,1,1,1,680,677,14,673,675,4,647,651,1,681

## Question 4
Add a column indicating if the earthquake happened in the ring of fire

In [59]:
rof = ['Alaska', 'Antarctica', 'Bolivia', 'California', 'Canada', 'Chile', 'Costa Rica', 'Ecuador' , 'Fiji', 'Guaetemala', 'Indonesia', 'Japan', 'Kermadec Islands', 'Mexico', 'New Zealand', 'Peru', 'Philippines', 'Russia', 'Taiwan', 'Tonga', 'Washington']

quakes['is_rof'] = quakes['parsed_place'].isin(rof)
quakes.sample(n=5)

,alert,cdi,code,detail,dmin,felt,gap,ids,mag,magType,...,time,title,tsunami,type,types,tz,updated,url,parsed_place,is_rof
9068,NaN,NaN,20257591,https://earthquake.usgs.gov/fdsnws/event/1/que...,NaN,NaN,NaN,",ak20257591,",0.90,ml,...,1537290603587,"M 0.9 - 29km NE of North Pole, Alaska",0,earthquake,",geoserve,origin,",-540.0,1537290858993,https://earthquake.usgs.gov/earthquakes/eventp...,Alaska,True
5889,NaN,NaN,00658354,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.24700,NaN,121.31,",nn00658354,",0.60,ml,...,1538010194986,"M 0.6 - 45km WNW of Gabbs, Nevada",0,earthquake,",geoserve,origin,phase-data,",-480.0,1538100308880,https://earthquake.usgs.gov/earthquakes/eventp...,Nevada,False
2840,NaN,NaN,37378706,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.01052,NaN,50.00,",ci37378706,",1.69,ml,...,1538638036540,"M 1.7 - 7km W of Holtville, CA",0,earthquake,",focal-mechanism,geoserve,nearby-cities,origin...",-480.0,1538678997700,https://earthquake.usgs.gov/earthquakes/eventp...,California,True
1746,NaN,0.0,73094821,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.01174,0.0,53.00,",nc73094821,",1.55,md,...,1538919947170,"M 1.6 - 4km W of Cobb, CA",0,earthquake,",dyfi,focal-mechanism,geoserve,nearby-cities,o...",-480.0,1539143823735,https://earthquake.usgs.gov/earthquakes/eventp...,California,True
7345,NaN,NaN,20261294,https://earthquake.usgs.gov/fdsnws/event/1/que...,NaN,NaN,NaN,",ak20261294,",1.80,ml,...,1537720197019,"M 1.8 - 86km SW of Kaktovik, Alaska",0,earthquake,",geoserve,origin,phase-data,",-540.0,1538071197876,https://earthquake.usgs.gov/earthquakes/eventp...,Alaska,True

## Question 5
Calculate the number of earthquakes inside and outside the Ring of Fire

In [76]:
quakes.groupby('is_rof')['is_rof'].count()
quakes['is_rof'].value_counts()

is_rof
True     7182
False    2150
Name: count, dtype: int64

## Question 6
Find the tsunami count along the Ring of Fire

In [73]:
print(quakes[quakes.is_rof]['tsunami'].sum())

45